### ISSUE TITLE
A problem in VPG

### ISSUE THREAD

**Issue by zhaoyingnan179346** [openai/spinningup#67] opened 2018-12-05 07:26 UTC
![2018-12-05 15-22-21](https://user-images.githubusercontent.com/16360301/49496840-de6e6500-f8a1-11e8-9f03-152ad5d04f51.png)
Why store the experience before excuting the action with a fake reward in the first step of each episode?

**Comment by andersahp** [comment] 2018-12-11 14:34
This feels weird to me too, it goes obs_0, act_0, rew_1, obs_1, act_1.....
So i feel like it should buf.store(..) after env.step() ?

**Comment by zhaoyingnan179346** [comment] 2018-12-12 08:35
> This feels weird to me too, it goes obs_0, act_0, rew_0, obs_1, act_1.....
> So i feel like it should buf.store(..) with the reward from env.step() (but not the observation). This way the reward is associated with the action that caused it?

I agree with you. We can do some experiments to verify it.

**Comment by jachiam** [comment] 2018-12-14 01:06
Same issue as #50, and I believe that this is in fact a bug. It doesn't break the math---it is equivalent to delaying a reward by one timestep, which makes the credit assignment problem slightly worse and makes an otherwise fully-observed environment into a partially-observed environment---but it may cause minor performance degradations.

I will hopefully land a patch in the not-distant future that includes a fix for this. However, when I ran some preliminary tests including the fix, I didn't see any substantial change in performance. Heistant to push the change until I have a full benchmark of the newest version (I want to make sure that the graphs on the Benchmarks page are always accurately tied to a code commit---all results must be reproducible).

**Comment by andersahp** [comment] 2018-12-14 01:19
Appreciate the answer. Thanks

**Comment by underactuated** [comment] 2018-12-27 21:58
@jachiam 

> It doesn't break the math---it is equivalent to delaying a reward by one timestep

It also makes you throw away the last reward (you replace it with 0 at the start), so if your trajectory is length N (state-action pairs), you only keep N-1 rewards.

Whether it is (in)significant bug, depends on what you want to do. For example, in my case, it is important to know the instantaneous reward function r(s,a). Even if it was not given to us (while often it is), it would be easy to learn it, but only if the arguments (s,a) are known, which is not the case in your implementation, since the values are shifted by 1.

Regardless of this issue, thank you very much for your work! I find the spinningup implementation by far the most useful (in comparison to other implementations of TRPO/PPO) due to its orderly structure and helpful comments. Great work!

**Comment by HareshMiriyala** [comment] 2019-02-19 15:17
Has the patch been applied ?

**Comment by scotthuang1989** [comment] 2019-02-22 09:06
any update on this? It's very confused....

**Comment by jachiam** [comment] 2020-01-31 07:00
This has been fixed in the latest version!

**Closed by jachiam** 2020-01-31 07:00 UTC
